### ISSUE TITLE
Twitter module sucks.

### ISSUE THREAD

**Issue by nol888** [nol888/kochira#2]
Reading from SSL socket very often throws exceptions, especially when there has been no activity on the socket for a while.

Should probably port other twitter module that uses requests and see if the buffering issues can be solved before reverting to raw sockets on top of twisted. (Gross)

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/nlum/python3.3/lib/python3.3/threading.py", line 901, in _bootstrap_inner
    self.run()
  File "/home/nlum/python3.3/lib/python3.3/threading.py", line 858, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nlum/kochira_caa/kochira_caa/twitter.py", line 102, in _follow_userstream
    for msg in stream.user():
  File "/home/nlum/kochira/lib/python3.3/site-packages/twitter/stream.py", line 85, in __iter__
    buf += recv_chunk(sock).decode('utf-8')
  File "/home/nlum/kochira/lib/python3.3/site-packages/twitter/stream.py", line 22, in recv_chunk
    remaining = int(buf[:crlf], 16)  # Decode the chunk size.
ValueError: invalid literal for int() with base 16: b'ja"}'
```

**Comment by nol888** [comment]
This is somehow fixed??????????? By switching hosting providers???????
